-- --------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- --------------------------------------------------------------------------------
DELIMITER $$

CREATE DEFINER=`62465_evila`@`%` PROCEDURE `calc_ranking_global`(in_dt_calc DATE, ds_locality varchar(200))
BEGIN

	DECLARE v_num_process_in INT(11);
	DECLARE v_num_process_out INT(11);







	DROP TABLE IF EXISTS TMP_MAST_RANKING;

	CREATE TABLE TMP_MAST_RANKING (
		ID_RESTAURANT int(11) NOT NULL,
		DT_SCORE date NOT NULL,
		ID_COUNTRY_3  varchar(3) DEFAULT NULL,
		ID_ADMIN_AREA_L1 varchar(200) DEFAULT NULL,
		ID_ADMIN_AREA_L2 varchar(200) DEFAULT NULL,
		ID_LOCALITY varchar(200) DEFAULT NULL,
		NUM_SCORE_GLOBAL decimal(10,7) NOT NULL,
		RANK int(11) NOT NULL,
		COUNTRY  varchar(3) DEFAULT NULL,
		ADMIN_AREA_L1 varchar(200) DEFAULT NULL,
		ADMIN_AREA_L2 varchar(200) DEFAULT NULL,
		LOCALITY varchar(200) DEFAULT NULL,
		PRIMARY KEY (ID_RESTAURANT)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
	IF ds_locality = '019' THEN -- BARCELONA 
		INSERT INTO TMP_MAST_RANKING (ID_RESTAURANT, DT_SCORE, ID_COUNTRY_3, ID_ADMIN_AREA_L1, ID_ADMIN_AREA_L2, ID_LOCALITY, NUM_SCORE_GLOBAL, RANK, COUNTRY,
									ADMIN_AREA_L1, ADMIN_AREA_L2, LOCALITY)
		SELECT ID_RESTAURANT, DT_SCORE, ID_COUNTRY_3, ID_ADMIN_AREA_L1, ID_ADMIN_AREA_L2, ID_LOCALITY, NUM_SCORE_GLOBAL,
			@restaurant:=CASE WHEN @country <> ID_COUNTRY_3 THEN 1 ELSE (CASE WHEN @admin_area_l1 <> ID_ADMIN_AREA_L1 THEN 1 ELSE (CASE WHEN @admin_area_l2 <> ID_ADMIN_AREA_L2 THEN 1 ELSE (CASE WHEN @locality <> ID_LOCALITY THEN 1 ELSE @restaurant+1 END) END) END ) END AS RANK,
			@country:=ID_COUNTRY_3 AS COUNTRY,
			@admin_area_l1:=ID_ADMIN_AREA_L1 AS ADMIN_AREA_L1,
			@admin_area_l2:=ID_ADMIN_AREA_L2 AS ADMIN_AREA_L2,
			@locality:=ID_LOCALITY AS LOCALITY

		FROM
			(SELECT @restaurant:= 0) a,
			(SELECT @country:= 0) b,
			(SELECT @admin_area_l1:= 0) c,
			(SELECT @admin_area_l2:= 0) d,
			(SELECT @locality:= 0) e,
			(SELECT * 
				FROM HIST_SCORE_GLOBAL
				WHERE DT_SCORE = in_dt_calc AND ID_LOCALITY = '019'
				ORDER BY ID_COUNTRY_3, ID_ADMIN_AREA_L1, ID_ADMIN_AREA_L2, ID_LOCALITY, NUM_SCORE_GLOBAL DESC) f;
	END IF;

	IF ds_locality = '079' THEN -- MADRID 
		INSERT INTO TMP_MAST_RANKING (ID_RESTAURANT, DT_SCORE, ID_COUNTRY_3, ID_ADMIN_AREA_L1, ID_ADMIN_AREA_L2, ID_LOCALITY, NUM_SCORE_GLOBAL, RANK, COUNTRY,
									ADMIN_AREA_L1, ADMIN_AREA_L2, LOCALITY)
		SELECT ID_RESTAURANT, DT_SCORE, ID_COUNTRY_3, ID_ADMIN_AREA_L1, ID_ADMIN_AREA_L2, ID_LOCALITY, NUM_SCORE_GLOBAL,
			@restaurant:=CASE WHEN @country <> ID_COUNTRY_3 THEN 1 ELSE (CASE WHEN @admin_area_l1 <> ID_ADMIN_AREA_L1 THEN 1 ELSE (CASE WHEN @admin_area_l2 <> ID_ADMIN_AREA_L2 THEN 1 ELSE (CASE WHEN @locality <> ID_LOCALITY THEN 1 ELSE @restaurant+1 END) END) END ) END AS RANK,
			@country:=ID_COUNTRY_3 AS COUNTRY,
			@admin_area_l1:=ID_ADMIN_AREA_L1 AS ADMIN_AREA_L1,
			@admin_area_l2:=ID_ADMIN_AREA_L2 AS ADMIN_AREA_L2,
			@locality:=ID_LOCALITY AS LOCALITY

		FROM
			(SELECT @restaurant:= 0) a,
			(SELECT @country:= 0) b,
			(SELECT @admin_area_l1:= 0) c,
			(SELECT @admin_area_l2:= 0) d,
			(SELECT @locality:= 0) e,
			(SELECT * 
				FROM HIST_SCORE_GLOBAL
				WHERE DT_SCORE = in_dt_calc AND ID_LOCALITY = '079'
				ORDER BY ID_COUNTRY_3, ID_ADMIN_AREA_L1, ID_ADMIN_AREA_L2, ID_LOCALITY, NUM_SCORE_GLOBAL DESC) f;
	END IF;
		
	IF ds_locality = '000' THEN -- OTHERS 
		INSERT INTO TMP_MAST_RANKING (ID_RESTAURANT, DT_SCORE, ID_COUNTRY_3, ID_ADMIN_AREA_L1, ID_ADMIN_AREA_L2, ID_LOCALITY, NUM_SCORE_GLOBAL, RANK, COUNTRY,
									ADMIN_AREA_L1, ADMIN_AREA_L2, LOCALITY)
		SELECT ID_RESTAURANT, DT_SCORE, ID_COUNTRY_3, ID_ADMIN_AREA_L1, ID_ADMIN_AREA_L2, ID_LOCALITY, NUM_SCORE_GLOBAL,
			@restaurant:=CASE WHEN @country <> ID_COUNTRY_3 THEN 1 ELSE (CASE WHEN @admin_area_l1 <> ID_ADMIN_AREA_L1 THEN 1 ELSE (CASE WHEN @admin_area_l2 <> ID_ADMIN_AREA_L2 THEN 1 ELSE (CASE WHEN @locality <> ID_LOCALITY THEN 1 ELSE @restaurant+1 END) END) END ) END AS RANK,
			@country:=ID_COUNTRY_3 AS COUNTRY,
			@admin_area_l1:=ID_ADMIN_AREA_L1 AS ADMIN_AREA_L1,
			@admin_area_l2:=ID_ADMIN_AREA_L2 AS ADMIN_AREA_L2,
			@locality:=ID_LOCALITY AS LOCALITY

		FROM
			(SELECT @restaurant:= 0) a,
			(SELECT @country:= 0) b,
			(SELECT @admin_area_l1:= 0) c,
			(SELECT @admin_area_l2:= 0) d,
			(SELECT @locality:= 0) e,
			(SELECT * 
				FROM HIST_SCORE_GLOBAL
				WHERE DT_SCORE = in_dt_calc AND ID_LOCALITY != '079' AND ID_LOCALITY != '019' 
				ORDER BY ID_COUNTRY_3, ID_ADMIN_AREA_L1, ID_ADMIN_AREA_L2, ID_LOCALITY, NUM_SCORE_GLOBAL DESC) f;
	END IF;

	UPDATE HIST_SCORE_GLOBAL Z INNER JOIN
		TMP_MAST_RANKING X
			ON Z.ID_RESTAURANT = X.ID_RESTAURANT
			AND Z.DT_SCORE = X.DT_SCORE
		SET Z.NUM_RANKING_GLOBAL = X.RANK;




END